//! Developer tooling (D30). Run with `cargo xtask <subcommand>` from the
//! workspace root. No runtime role: everything here runs on a developer
//! machine and never ships.

use std::path::{Path, PathBuf};

/// Required header on every generated file (Part 2 acceptance): ts-rs
/// emits the type body, this tool stamps provenance so a hand-edit is
/// recognisable as one.
const HEADER: &str = "// This file was generated by cargo xtask generate-types\n// Do not edit \u{2014} run cargo xtask generate-types to regenerate\n";

fn workspace_root() -> PathBuf {
    // xtask/Cargo.toml lives exactly one level below the workspace root,
    // so this holds regardless of the shell's working directory.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives one level below the workspace root")
        .to_path_buf()
}

fn generated_dir() -> PathBuf {
    workspace_root().join("client").join("src").join("types").join("generated")
}

/// Prepend [`HEADER`] to every generated `.ts` file that lacks it.
/// Returns the number of `.ts` files present.
fn stamp_headers(dir: &Path) -> usize {
    let mut count = 0;
    let entries = std::fs::read_dir(dir).expect("generated dir reads");
    for entry in entries {
        let path = entry.expect("dir entry reads").path();
        if path.is_dir() {
            count += stamp_headers(&path);
            continue;
        }
        if path.extension().is_some_and(|ext| ext == "ts") {
            let body = std::fs::read_to_string(&path).expect("generated file reads");
            if !body.contains("cargo xtask generate-types") {
                std::fs::write(&path, format!("{HEADER}{body}")).expect("header writes");
            }
            count += 1;
        }
    }
    count
}

fn generate_types() {
    let dir = generated_dir();
    std::fs::create_dir_all(&dir).expect("generated dir creates");
    // The registry lives in the server crate (server/src/ts_export.rs):
    // ts-rs 10.1 has no global "export everything" entry point, and the
    // per-type export attribute would emit file-writing tests, so the
    // owning crate enumerates its boundary types explicitly.
    server::ts_export::export_all(&dir).expect("type export succeeds");
    let count = stamp_headers(&dir);
    println!("Generated {count} types to client/src/types/generated/");
}

fn usage() -> ! {
    eprintln!("usage: cargo xtask generate-types");
    std::process::exit(1);
}

fn main() {
    let mut args = std::env::args().skip(1);
    match args.next().as_deref() {
        Some("generate-types") if args.next().is_none() => generate_types(),
        _ => usage(),
    }
}
